const links = {
  github: "https://github.com/VeloKode/VELO-KODE",
  twitter: "",
  linkedin: "",
  discord: "",
  authorsWebsite: "https://velokode.com",
  authorsGitHub: "https://github.com/velokode",
  openGraphImage: "https://velokode.com/opengraph-image.png",
  manifestFile: "https://velokode.com/site.webmanifest",
}

export const siteConfig = {
  name: "VeloKode",
  nameLong: "VeloKode Software House",
  description: "",
  links,
  url: "https://velokode.com",
  ogImage: links.openGraphImage,
  author: "@velokode",
  hostingRegion: "fra1",
  keywords: [
    "Software House",
    "Web Development Agency",
    "Software Development Agency",
    "Software developer",
    "Programmer",
    "Web developer",
    "Full stack developer",
    "Frontend developer",
    "Backend developer",
    "React developer",
    "AI engineer",
    "Machine learning engineer",
    "Data scientist",
    "Data engineer",
    "Python developer",
    "JavaScript developer",
    "TypeScript developer",
    "Node.js developer",
    "Blockchain developer",
  ],
}
